services:
  nest-app:
    container_name: nest-CRM-app-container
    build:
      context: .
      dockerfile: Dockerfile

    env_file:
      - back_nest/environments/local.env
    ports:
      - '${APP_PORT:-5000}:5000' # Map port 5000 of the container to port 5000 on the host
    volumes:
      - ./back_nest:/app_nest # Sync project directory to container
      - /app_nest/node_modules # Ignore node_modules on the host
    restart: on-failure
    command: npm run start:local # Run the NestJS app



