export enum OrdersSortByEnum {
  ID = 'id',
  NAME = 'name',
  SURNAME = 'surname',
  EMAIL = 'email',
  PHONE = 'phone',
  AGE = 'age',
  COURSE = 'course',
  COURSE_FORMAT = 'course_format',
  COURSE_TYPE = 'course_type',
  SUM = 'sum',
  ALREADY_PAID = 'alreadyPaid',
  UTM = 'utm',
  MSG = 'msg',
  MANAGER = 'manager',
  GROUP = 'group',
  STATUS = 'status',
  CREATED_AT = 'created_at',
}
